hmrc/agent-epaye-registration-frontend

app/uk/gov/hmrc/agentepayeregistrationfrontend/views/addressDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/agentDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/contactDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/main_template.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/start.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/summary.scala.html
conf/application.conf
conf/messages

Removed unnecessary fieldsets, added correct heading classes, replaced @input helpers on hidden inputs with html inputs (failing accessibility on WAVE), added BETA banner, added article layout and bumped up assets-frontend.

[SS][APB-1218] updated markup to fix failing accessability issues

---

app/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/AgentEpayeRegistrationController.scala
conf/app.routes
conf/messages
it/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/AgentEpayeRegistrationControllerISpec.scala

Adding /start to app.routes and making the root context redirect to it. 
Adding some spec specific validation messages for maximum length and email address

[APB-1021][JR] Fixing copy and other issues found in QA

---

conf/messages

[APB-1496][LS] Added spaces between characters in error message to match

---

it/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/AgentEpayeRegistrationControllerISpec.scala

Fix failing test after page title changes

[BK][APB-2009] fix failing test

---

app/uk/gov/hmrc/agentepayeregistrationfrontend/views/registration_confirmation.scala.html

[APB-2106][SS] fixed colour contrast accessibility issue on confirmation page

---

app/FrontendModule.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/connectors/FrontendAuthConnector.scala
build.sbt
project/plugins.sbt
run_local.sh

dependAgentFE - upgrade agent epaye registration frontend dependancies to latest
**Maintenance
Upgrading dependencies and plugins to latest versions as per catalogue

dependAgengFE updating dependencies

---

app/FrontendModule.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/connectors/FrontendAuthConnector.scala
build.sbt
project/plugins.sbt

**Bug fix**
Update of dependencies and play versions for security upgrade in opra frontend

play security upgrade

---

app/ErrorHandler.scala
app/FrontendModule.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/config/AppConfig.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/connectors/AgentEpayeRegistrationConnector.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/connectors/FrontendAuthConnector.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/AgentEpayeRegistrationController.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/package.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/testonly/TestOnlyController.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/models/Address.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/models/RegistrationRequest.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/service/AgentEpayeRegistrationService.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/addressDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/agentDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/contactDetails.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/error_prefix.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/error_template.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/main_template.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/registration_confirmation.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/start.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/summary.scala.html
build.sbt
conf/application.conf
project/build.properties
project/plugins.sbt
test/ErrorHandlerSpec.scala
test/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/FieldMappingsSpec.scala
test/uk/gov/hmrc/agentepayeregistrationfrontend/controllers/RegistrationRequestFormSpec.scala
test/uk/gov/hmrc/agentepayeregistrationfrontend/models/AddressSpec.scala
test/uk/gov/hmrc/agentepayeregistrationfrontend/views/ViewsSpec.scala

Updated dependencies for ```agent-epaye-registration-frontend```.

DL-2687 - OPRA Dependency Updates

---

README.md
build.sbt
project/build.properties
project/plugins.sbt

**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

DL-3583 - Dependency Updates

---

app/ErrorHandler.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/error_template.scala.html
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/govuk_wrapper.scala.html
build.sbt
conf/application.conf

Added a11y statement link to the footer/updated play-ui to 8.12. a11y statement PR: https://github.com/hmrc/accessibility-statement-frontend/pull/133

DL-4232 - A11y statement functionality for OPRA

---

.travis.yml
build.sbt

DL-4479 - updated sbt and scala version

---

app/uk/gov/hmrc/agentepayeregistrationfrontend/config/AppConfig.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/govuk_wrapper.scala.html
conf/application.conf

DL-4988 - GTM Migration

---

app/uk/gov/hmrc/agentepayeregistrationfrontend/config/AppConfig.scala
app/uk/gov/hmrc/agentepayeregistrationfrontend/views/govuk_wrapper.scala.html
conf/application.conf

Removed GA and GTM. Tracking has been added.

DL-5016 - Removed GA code and implemented tracking

---

conf/application.conf

DL-5208 - Removed redundant config keys

---

build.sbt

**Bug fix**
Removed the auth-client dependency as it is not used

DL-5588 Removed unused `auth-client` dependency

---

.gitignore
app/views/ConfirmationView.scala.html
conf/messages.en

- []  I've executed the acceptance test pack locally to ensure there are no functional regressions

DL-6135 - Added feedback link to confirmation page

---

app/viewmodels/CheckYourAnswersHelper.scala

- Added visually hidden text
- Checked screen reader reads the field name in each link

DL-6193 - Add visually hidden text to 'Check' links

---

project/AppDependencies.scala

No uses of CTheM, raised dependency versions

DL-12318 - HMRC wording - OPRA

---

.metals/metals.lock.db
app/views/YourAgentNameView.scala.html
app/views/YourBusinessAddressView.scala.html
app/views/YourContactDetailsView.scala.html

DL-14843: Added autocomplete to input fields

DL-14843: Added autocomplete to input fields

---

app/forms/mappings/Formatters.scala
app/utils/EmailAddress.scala
app/utils/StringValue.scala
project/AppDependencies.scala
project/plugins.sbt

Version change done in bootstrap,mongo,sbt-built,org.playframework

DL-15071: Upgrade dependencies version to latest

---

it/test/resources/it.application.conf
project/AppDependencies.scala

DL-15279:Rectify the bobby violation

DL-15279:Rectify the bobby violation

---

app/viewmodels/govuk/InputFluency.scala
app/views/YourContactDetailsView.scala.html

DL-16642: Added correct input type

DL-16642: Added correct input type
